ArabalarDunyasii/Models/Araba.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ArabalarDunyasii.Models
{
    public class Araba
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="{0} alanı zorunludur. ")]
        [MaxLength(200, ErrorMessage ="{0} alanı en fazla {1} karakter olabilir.")]
        [Display(Name ="Model")]
        public string Model { get; set; }
        [Required(ErrorMessage ="{0} alanı zorunludur.")]
        [Range(1900,2100, ErrorMessage ="{0} {1} ile {2} aralığında olmalıdır.")]
        [Display(Name ="Yıl")]
        public int? Yil { get; set; }
    }
}

ArabalarDunyasii/Models/ErrorViewModel.cs
using System;

namespace ArabalarDunyasii.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ArabalarDunyasii/Models/UygulamaDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArabalarDunyasii.Models
{
    public class UygulamaDbContext : DbContext
    {
        public DbSet<Araba> Arabalar { get; set; }

        public UygulamaDbContext(DbContextOptions<UygulamaDbContext> options) : base(options)
        {
           
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Araba>().HasData(
                new Araba() { Id = 1, Model = "Volkswagen Passat 1.6 TDI BlueMotion ComfortLine", Yil = 2018 },
                new Araba() { Id = 2, Model = "Seat Ibiza 1.6 Stella", Yil = 2001 },
                new Araba() { Id = 3, Model = "Renault Fluence 1.5 dCi Authentique", Yil = 2011 },
                new Araba() { Id = 4, Model = "Seat Leon 1.6 TDI CR Style", Yil = 2014 }
                );
            base.OnModelCreating(modelBuilder);
        }
    }
}

ArabalarDunyasii/Controllers/ArabalarController.cs
using ArabalarDunyasii.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ArabalarDunyasii.Controllers
{
    public class ArabalarController : Controller
    {
        private readonly UygulamaDbContext db;

        public ArabalarController(UygulamaDbContext db)
        {
            this.db = db;
        }
        public IActionResult Yeni()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Yeni(Araba araba)
        {
            if (ModelState.IsValid)
            {
                db.Add(araba);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
        
        public IActionResult Sil(int id)
        {
            return View(db.Arabalar.Find(id));
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SilOnaylandi(int id)
        {
            Araba araba = db.Arabalar.Find(id);
            db.Remove(araba);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Duzenle(int id)
        {
            return View(db.Arabalar.Find(id));
        }
        
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Duzenle (Araba araba)
        {
            if (ModelState.IsValid)
            {
                db.Update(araba);
                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }

            return View();
            
        }
    }
}

ArabalarDunyasii/Controllers/HomeController.cs
using ArabalarDunyasii.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ArabalarDunyasii.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UygulamaDbContext db;

        public HomeController(ILogger<HomeController> logger, UygulamaDbContext db)
        {
            _logger = logger;
            this.db = db;
        }

        public IActionResult Index()
        {
            return View(db.Arabalar.ToList());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ArabalarDunyasii/Views/Arabalar/Duzenle.cshtml
@model Araba

@{
    ViewData["Title"] = "Düzenle";
}

<h1>Araba Düzenle</h1>

<div asp-validation-summary="All" class="alert alert-danger"></div>


<form method="post" asp-controller="Arabalar" asp-action="Duzenle">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Model"></label>
        <input asp-for="Model" type="text" class="form-control" />
        <span asp-validation-for="Model" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Yil"></label>
        <input asp-for="Yil" type="text" class="form-control" />
        <span asp-validation-for="Yil" class="form-text text-danger"></span>
    </div>
    <button class="btn btn-primary">Kaydet</button>
</form>

ArabalarDunyasii/Views/Arabalar/Sil.cshtml
@model Araba
@{ 
    ViewData["Title"] = "Araba Silme Onayı";
}

<h1>Silme Onayı</h1>

<form asp-controller="Arabalar" asp-action="SilOnaylandi">
    <input asp-for="Id" type="hidden"/>
    <p>
        "@Model.Model (@Model.Yil)" adlı araba silinecektir. Onaylıyor Musunuz?
    </p>
    <button class="btn btn-danger">Silmeyi Onayla</button>
</form>

<a asp-controller="Home" asp-action="Index">Vazgeçtim, beni arabalar listesine götür.</a>

ArabalarDunyasii/Views/Arabalar/Yeni.cshtml
@model Araba
@{
    ViewData["Title"] = "Yeni Araba";
}

<h1>Yeni Araba</h1>

<div asp-validation-summary="All" class="alert alert-danger"></div>

<form action="/" method="post"></form>
<form method="post" asp-controller="Arabalar" asp-action="Yeni">
    <div class="form-group">
        <label asp-for="Model"></label>
        <input asp-for="Model" type="text" class="form-control" />
        <span asp-validation-for="Model" class="form-text text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Yil"></label>
        <input asp-for="Yil" type="text" class="form-control" />
        <span asp-validation-for="Yil" class="form-text text-danger"></span>
    </div>
    <button class="btn btn-primary">Ekle</button>
</form>

ArabalarDunyasii/Views/Home/Index.cshtml
@model List<Araba>
@{
    ViewData["Title"] = "Home Page";
}
<div class="d-flex align-items-center">
    <h1 class="mr-auto">Arabalar</h1>
    <a asp-controller="Arabalar" asp-action="Yeni" class="btn btn-primary">
        <i class="fas fa-plus"></i>
    </a>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Model</th>
            <th>Yıl</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.Id</td>
            <td>@item.Model</td>
            <td>@item.Yil</td>
            <td>
                <a asp-controller="Arabalar" asp-action="Sil" asp-route-id="@item.Id" class="btn btn-danger">
                    <i class="fas fa-trash"></i>
                </a>

                <a asp-controller="Arabalar" asp-action="Duzenle" asp-route-id="@item.Id" class="btn btn-sm btn-info">
                    <i class="fas fa-pen"></i>
                </a>
            </td>

        </tr>
        }

    </tbody>
</table>

ArabalarDunyasii/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArabalarDunyasii</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ArabalarDunyasii</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ArabalarDunyasii - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>